apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-first-app
  name: my-first-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-first-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-first-app
  name: my-first-app
spec:
  selector:
    matchLabels:
      app: my-first-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-first-app
    spec:
      containers:
      - image: ghcr.io/logano02/my-first-app:sha256-ad4fa14a59c85ed43a4e9dc1f3d83cc5b7df3f0abde2ee6570d03bd8ff9f2fe7.sig
        name: my-first-app
        ports:
        - containerPort: 80
          name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-first-app
spec:
  ingressClassName: nginx
  rules:
  - host: theng.training.dnsfor.me
    http:
      paths:
      - backend:
          service:
            name: my-first-app
            port:
              number: 80
        path: /
        pathType: Prefix
